gra/gra/urls.py
from django.contrib import admin
from django.urls import path,include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('others/', include('others.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gra/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("<single_slug>", views.single_slug, name="single_slug"),
#     path("forms/", views.forms_download, name="forms"),
]

gra/others/urls.py
from django.urls import path
from . import views

app_name = "others"

urlpatterns = [
    path("legals/", views.legals, name="legals"),
    path("publications/", views.publications, name="publications"),
    path("offices/", views.offices, name="offices"),
    path("contacts/", views.contacts, name="contacts"),
]

gra/main/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class MainCategory(models.Model):
	"""docstring for MianCategory"""

	main_category=models.CharField(max_length=200)
	cat_summary = models.CharField(max_length=200)
	cat_slug = models.CharField(max_length=200)
	image=models.ImageField( default = 'img/img.jpg')

	class Meta:
		verbose_name_plural = "Categories"

	def __str__(self):
		return self.main_category





class ArticleSeries(models.Model):
	article_series = models.CharField(max_length=200)
	main_category = models.ForeignKey(MainCategory, default=1, verbose_name="Category", on_delete=models.SET_DEFAULT)
	series_summary = models.CharField(max_length=200)

	class Meta:
		verbose_name_plural = "Series"

	def __str__(self):
		return self.article_series





class MainArticle(models.Model):
	article_title = models.CharField(max_length=200)
	article_content = models.TextField()
	date_published = models.DateTimeField("date published", default=datetime.now())

	article_series = models.ForeignKey(ArticleSeries, default=1, verbose_name="Series", on_delete=models.SET_DEFAULT)
	article_slug = models.CharField(max_length=200, default=1)
	thumb = models.ImageField(default='default.png', blank=True)

	def __str__(self):
		return self.article_title


	# def snippet(self):
 #        return self.body[:50] + '...'




        

gra/others/models.py
from django.db import models

# Create your models here.
class legals_pannel(models.Model):
	title = models.CharField(max_length=200)
	content = models.TextField()
	thumb = models.ImageField(default='default.png')

	def __str__(self):
		return self.title




class publications_pannel(models.Model):
	title = models.CharField(max_length=200)
	content = models.TextField()
	thumb = models.ImageField(default='default.png')

	def __str__(self):
		return self.title





class contacts_pannel(models.Model):
	title = models.CharField(max_length=200)
	content = models.TextField()
	thumb = models.ImageField(default='default.png')

	def __str__(self):
		return self.title




class locations_pannel(models.Model):
	title = models.CharField(max_length=200)
	content = models.TextField()
	thumb = models.ImageField(default='default.png')

	def __str__(self):
		return self.title

gra/main/views.py
from django.shortcuts import render,redirect
from .models import MainCategory,ArticleSeries,MainArticle





# Create your views here.
def homepage(request):
    return render(request=request,
                  template_name="main/categories.html",
                  context={"categories": MainCategory.objects.all})






def single_slug(request, single_slug):
    # first check to see if the url is in categories.

    categories = [c.cat_slug for c in MainCategory.objects.all()]
    if single_slug in categories:
        matching_series = ArticleSeries.objects.filter(main_category__cat_slug=single_slug)
        series_urls = {}

        for m in matching_series.all():
            part_one = MainArticle.objects.filter(article_series__article_series=m.article_series).earliest("date_published")
            series_urls[m] = part_one.article_slug

        return render(request=request,
                      template_name='main/category.html',
                      context={"tutorial_series": matching_series, "part_ones": series_urls})

    article = [t.article_slug for t in MainArticle.objects.all()]

    if single_slug in article:
        this_article = MainArticle.objects.get(article_slug=single_slug)
        article_from_series = MainArticle.objects.filter(article_series__article_series=this_article.article_series).order_by('date_published')
        this_article_idx = list(article_from_series).index(this_article)

        return render(request=request,
                      template_name='main/articles.html',
                      context={"article": this_article,
                               "sidebar": article_from_series,
                               "this_art_idx": this_article_idx})


        

gra/others/views.py
from django.shortcuts import render,redirect
from .models import legals_pannel,publications_pannel,contacts_pannel,locations_pannel

# Create your views here.


def legals(request):
    return render(request=request,
                  template_name="others/legals.html",
                  context={"leg_pannel": legals_pannel.objects.all()})


def publications(request):
    return render(request=request,
                  template_name="others/publications.html",
                  context={"pub_pannel": publications_pannel.objects.all})




def offices(request):
    return render(request=request,
                  template_name="others/offices.html",
                  context={"loc_pannel": locations_pannel.objects.all})



def contacts(request):
    return render(request=request,
                  template_name="others/contacts.html",
                  context={"cont_pannel": contacts_pannel.objects.all})

gra/main/templates/main/articles.html
{% extends 'main/header.html' %}

{% block content %}

    <div class="row z-depth-1" >

        <div class="col s12, m8, l8">
            <h3>{{article.article_title}}</h3>
            <p style="font-size:70%">Published {{article.date_published}}</p>
            {{article.article_content|safe}}
        </div>

        <div class="col s12 m4 l4">
            <ul class="collapsible popout">
                {% for article in sidebar %}
                    {% if forloop.counter0 == this_art_idx %}
                        <li class="active">
                            <div class="collapsible-header">{{article.article_title}}<br>(currently viewing)</div>
                        </li>
                    {% else %}
                        <li>
                            <div class="collapsible-header">{{article.article_title}}</div>
                            <div class="collapsible-body">
                                <p><a href="/{{article.article_slug}}"><button class="btn waves-effect waves-light right-align" style="background-color:yellow; color:black">Go</button></a></p>

                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>

    </div>


    <footer class="page-footer purple darken-4">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>

{% endblock %}

gra/main/templates/main/categories.html
{% extends 'main/header.html' %}

{% block content %}



<!-- slider  -->



<!-- <p>Slideshow 2:</p>
<div class="slideshow-container">
  <div class="mySlides2">
    <img src="img_band_chicago.jpg" style="width:100%">
  </div>

  <div class="mySlides2">
    <img src="img_band_la.jpg" style="width:100%">
  </div>

  <div class="mySlides2">
    <img src="img_band_ny.jpg" style="width:100%">
  </div>

  <a class="prev" onclick="plusSlides(-1, 1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1, 1)">&#10095;</a>
</div> -->














    <div class="row z-depth-1">


      <div class="slideshow-container">
        <div class="mySlides1">
          <img src="VAT.jpg" style="width:90%"/>
          <span>IMAGE 1</span>
        </div>

        <div class="mySlides1">
          <img src="main/img/laws.jpeg" style="width:90%"/>
           <span>IMAGE 2</span>
        </div>

        <div class="mySlides1">
          <img src="main/img/nhil.jpg" style="width:90%"/>
            <span>IMAGE 3</span>
          
        </div>

        <a class="prev" onclick="plusSlides(-1, 0)">&#10094;</a>
        <a class="next" onclick="plusSlides(1, 0)">&#10095;</a>
      </div>





 <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Card Title</span>
          <p>I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup to use effectively.</p>
        </div>
        <div class="card-action">
          <a href="#">This is a link</a>
          <a href="#">This is a link</a>
        </div>
      </div>
    </div>
  </div>

        {% for cat in categories %}
            <div class="col s12 m6 l4">
                <a href="{{cat.cat_slug}}", style="color:#000">
                    <div class="card hoverable">
                      <div class="card-image">

                        <img src="{{cat.image.url}}" alt="">

                      </div>

                        <div class="card-content">

                            <span class="card-title">{{cat.main_category}}</span>
                            <!--<p style="font-size:70%">Published {{tut.tutorial_published}}</p>-->
                            <p>{{cat.cat_summary}}</p>
                        </div>
                        <div class="card-action">

                          <a href="">VIEW</a>
                        </div>



                    </div>
                </a>
            </div>
        {% endfor %}
    </div>



 <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Card Title</span>
          <p>I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup to use effectively.</p>
        </div>
        <div class="card-action">
          <a href="#">This is a link</a>
          <a href="#">This is a link</a>
        </div>
      </div>
    </div>
  </div>



<footer class="page-footer purple darken-4">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>
            



{% endblock %}

gra/main/templates/main/category.html
{% extends 'main/header.html' %}

{% block content %}

    <div class="row">
        {% for art, partone in part_ones.items %}

            <div class="col s12 m6 l4">
                <a href="{{partone}}", style="color:#000">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div class="card-title">{{art.article_series}}</div>
                            <!--<p style="font-size:70%">Published {{art.date_published}}</p>-->
                            <p>{{art.series_summary}}</p>
                        </div>

                        <div class="card-action">

                          <a href="">More details</a>

                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>


    <footer class="page-footer purple darken-4">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>
{% endblock %}

gra/main/templates/main/header.html
<head>
    {% load static from staticfiles %}
    <!-- Prism CSS -->
    <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

   

<!-- slider css style -->

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing: border-box}
.mySlides1, .mySlides2 {display: none;}
img {vertical-align: middle;}

/* Slideshow container */
.slideshow-container {
  max-width: 1000px;
  position: relative;
  margin: auto;
}

/* Next & previous buttons */
.prev, .next {
  cursor: pointer;
  position: absolute;
  top: 50%;
  width: auto;
  padding: 16px;
  margin-top: -22px;
  color: white;
  font-weight: bold;
  font-size: 18px;
  transition: 0.6s ease;
  border-radius: 0 3px 3px 0;
  user-select: none;
}

/* Position the "next button" to the right */
.next {
  right: 0;
  border-radius: 3px 0 0 3px;
}

/* On hover, add a grey background color */
.prev:hover, .next:hover {
  background-color: #f1f1f1;
  color: black;
}
</style>



</head>

<body>
  
    <nav>
      <div class="nav-wrapper  "
      <a href="/" class="brand-logo  ">G.R.A logo</a>
      

      <!-- sidebar menu -->
      <a href="#" class="sidenav-trigger" data-target="mobile-links">
        <i class="material-icons">menu</i>
      </a>
      <!-- navbar in desktop -->
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        {% include 'main/includes/navbar.html' %}
      </ul>
    </div>
  </nav>

<!-- side bar activated in mobile form -->
  <ul class="sidenav" id="mobile-links">
        
        <li><a href="/">Home</a></li>
        <li><a href="/forms">Forms</a></li>
        <li><a href="{% url 'others:legals' %}">Legal Resources</a></li>
        <li><a href="{% url 'others:publications' %}">Publications</a></li>
        <li><a href="{% url 'others:offices' %}">Office Locations</a></li>
        <li><a href="{% url 'others:contacts' %}">Contact Us</a></li>
  </ul>

  {% include 'main/includes/messages.html' %}

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>



<!-- Compiled and minified JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
  <script>
    $(document).ready(function(){
      $('.sidenav').sidenav();
    });
  </script>

   <!-- Compiled and minified JavaScript for Materialize CSS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</body>

<script src="{% static "tinymce/js/prism.js" %}"></script>
<script>M.AutoInit();</script>

<!-- slider script -->

<script>
var slideIndex = [1,1];
var slideId = ["mySlides1", "mySlides2"]
showSlides(1, 0);
showSlides(1, 1);

function plusSlides(n, no) {
  showSlides(slideIndex[no] += n, no);
}

function showSlides(n, no) {
  var i;
  var x = document.getElementsByClassName(slideId[no]);
  if (n > x.length) {slideIndex[no] = 1}    
  if (n < 1) {slideIndex[no] = x.length}
  for (i = 0; i < x.length; i++) {
     x[i].style.display = "none";  
  }
  x[slideIndex[no]-1].style.display = "block";  
}
</script>

gra/main/templates/main/includes/navbar.html
   <nav>
    <div class="nav-wrapper">
      <!-- <a href="/" class="brand-logo">Tutorials!</a> -->
      <ul id="nav-mobile" class="right hide-on-med-and-down purple lighten-2">
        <li><a href="/">Home</a></li>
        <li><a href="/forms">Forms</a></li>
        <li><a href="{% url 'others:legals' %}">Legal Resources</a></li>
        <li><a href="{% url 'others:publications' %}">Publications</a></li>
        <li><a href="{% url 'others:offices' %}">Office Locations</a></li>
        <li><a href="{% url 'others:contacts' %}">Contact Us</a></li>
        

      </ul>
    </div>

  </nav>

gra/others/templates/others/contacts.html
{% extends 'main/header.html' %}

{% block content %}

<div class="row" z-depth-1>
  {% for p in cont_pannel %}

	<div class="col s12, m8, l8">
		<img src="{{ p.thumb.url }}" />
		<h3>{{p.title}}</h3>
		<!-- <p style="font-size:70%">Published {{other_items.date_published}}</p> -->
		{{p.content|safe}}
	</div>
  {% endfor %}
</div>


<div class="col s12, m8, l8">
  <h3>{{article.article_title}}</h3>
  <p style="font-size:70%">Published {{article.date_published}}</p>
  {{article.article_content|safe}}
</div>


<footer class="page-footer purple darken-4">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>

{% endblock %}

gra/others/templates/others/legals.html
{% extends 'main/header.html' %}

{% block content %}

<div class="row" z-depth-1>

	{% for p in leg_pannel %}

  <div class="col s12, m8, l8">
    <img src="{{ p.thumb.url }}" />
    <h3>{{p.title}}</h3>
    <!-- <p style="font-size:70%">Published {{other_items.date_published}}</p> -->
    {{p.content|safe}}
  </div>
  {% endfor %}
</div>

<footer class="page-footer purple darken-4">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>

{% endblock %}

gra/others/templates/others/offices.html
{% extends 'main/header.html' %}

{% block content %}

<div class="row" z-depth-1>


	{% for p in loc_pannel %}

  <div class="col s12, m8, l8">
    <img src="{{ p.thumb.url }}" />
    <h3>{{p.title}}</h3>
    <!-- <p style="font-size:70%">Published {{other_items.date_published}}</p> -->
    {{p.content|safe}}
  </div>
  {% endfor %}
</div>

<footer class="page-footer purple darken-4">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>
{% endblock %}

gra/others/templates/others/publications.html
{% extends 'main/header.html' %}

{% block content %}

<div class="row" z-depth-1>


	{% for p in pub_pannel %}

  <div class="col s12, m8, l8">
    <img src="{{ p.thumb.url }}" />
    <h3>{{p.title}}</h3>
    <!-- <p style="font-size:70%">Published {{other_items.date_published}}</p> -->
    {{p.content|safe}}
  </div>
  {% endfor %}
</div>

<footer class="page-footer purple darken-4">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>

{% endblock %}